In [1]:
import bs4

In [2]:
import utils

utils.download_favicon?

Signature: utils.download_favicon(url, save_path=None)
Docstring:
Download favicon from a website using requests and BeautifulSoup.

Args:
    url (str): The website URL to get favicon from
    save_path (str, optional): Path to save the favicon file.
                               If None, returns bytes.

Returns:
    bytes or None: If save_path is None, returns the favicon bytes.
                   If save_path is provided, returns None after saving.
                   Returns None if favicon cannot be found.
File:      ~\downloads\workspace\poc\deepseek-tools\notebooks\utils.py
Type:      function

In [3]:
for org in "pytorch lichess gnu".split():
    utils.download_favicon(f"{org}.org", f"{org}.ico")

Favicon saved to: pytorch.ico
Favicon saved to: lichess.ico
Error downloading favicon: HTTPSConnectionPool(host='gnu.org', port=443): Read timed out. (read timeout=10)

In [4]:
utils.convert_image?

Signature:
utils.convert_image(
    input_data: Union[str, pathlib._local.Path, bytes],
    output_format: str,
    output_path: Union[str, pathlib._local.Path, NoneType] = None,
    **kwargs,
) -> Optional[bytes]
Docstring:
Convert an image between formats.

Args:
    input_data: Image source - can be a string path, pathlib.Path, or bytes
    output_format: Target format (e.g., 'PNG', 'JPEG', 'WEBP', 'BMP', 'TIFF')
    output_path: Optional path to save the converted image. If not provided,
                returns bytes of the converted image.
    **kwargs: Additional arguments passed to Image.save() (e.g., quality, optimize)

Returns:
    bytes if output_path is None, else None

Raises:
    ValueError: If input format is invalid or unsupported
    FileNotFoundError: If input file doesn't exist
    PIL.UnidentifiedImageError: If image data is corrupted or invalid

Examples:
    # Convert from file path to bytes
    result_bytes = convert_image('input.jpg', 'PNG')

    # Convert from bytes to file
    with open('input.jpg', 'rb') as f:
        image_bytes = f.read()
    convert_image(image_bytes, 'WEBP', 'output.webp')

    # Convert between paths
    convert_image('input.png', 'JPEG', 'output.jpg', quality=85)

    # Convert from pathlib.Path
    from pathlib import Path
    convert_image(Path('input.bmp'), 'TIFF', 'output.tiff')
File:      ~\downloads\workspace\poc\deepseek-tools\notebooks\utils.py
Type:      function

In [5]:
utils.convert_image("lichess.ico", "png", "lichess.png")

ValueError: Failed to load image: cannot identify image file 'lichess.ico'

In [2]:
from pathlib import Path

page = bs4.BeautifulSoup(Path("data/Previous PyTorch Versions.htm").read_bytes())

In [3]:
def all_nodes(node):
    child_count = 0
    yield node
    if hasattr(node, "children"):
        for child in node.children:
            yield from all_nodes(child)

import pandas as pd
sr = pd.Series(all_nodes(page))
sr

0       [html, \n, [[\n, <meta content="text/html; cha...
1                                                    html
2                                                      \n
3       [[\n, [], [], \n, [], [], [(window.NREUM||(NRE...
4       [\n, [], [], \n, [], [], [(window.NREUM||(NREU...
                              ...
5814    window.NREUM||(NREUM={});NREUM.info={"beacon":...
5815                                                   \n
5816                                                   []
5817                                                   \n
5818     plugin=object-cache-pro client=phpredis metri...
Length: 5819, dtype: object

In [4]:
tag_with_attr = page.select(".ocm-dropdown-arrow")[0]
tag_with_attr

In [5]:
tag_with_attr.attrs

{'class': ['ocm-dropdown-arrow']}

In [9]:
utils.object_to_dict(tag_with_attr, flatten_dict_sep="__", flatten_list_sep="_", max_depth=3)

{'attrs__class_0': 'ocm-dropdown-arrow',
 'can_be_empty_element': False,
 'decomposed': False,
 'hidden': False,
 'is_empty_element': False,
 'known_xml': False,
 'name': 'span',
 'previous': '\n',
 'previousSibling': '\n',
 'previous_element': '\n',
 'previous_sibling': '\n',
 'sourceline': 2696,
 'sourcepos': 0,
 'text': ''}

In [10]:
df_nodes = pd.DataFrame(utils.object_to_dict(x, flatten_dict_sep="__", flatten_list_sep="_", max_depth=3, pyid=id, type=type) for x in all_nodes(page)).set_index("pyid")
df_nodes.to_csv("all_nodes_with_id.csv")
df_nodes

,ASCII_SPACES,DEFAULT_BUILDER_FEATURES_0,DEFAULT_BUILDER_FEATURES_1,ROOT_TAG_NAME,can_be_empty_element,contains_replacement_characters,contents_0,contents_1,contents_3,contents_4,...,attrs__data-has-widgets,attrs__data-layout,attrs__aria-modal,attrs__data-dropdown-func,attrs__data-back-txt,attrs__data-prepend-menu-mobile,attrs__version,attrs__cx,attrs__cy,attrs__r
pyid,,,,,,,,,,,,,,,,,,,,,
2092614782992,\n\t \r,html,fast,[document],False,False,html,\n,\n,plugin=object-cache-pro client=phpredis metri...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2092614963024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2092614962928,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2092614784672,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2092614180752,NaN,NaN,NaN,NaN,False,NaN,\n,NaN,\n,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2092621284656,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2092621284752,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2092621317968,NaN,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2092621284848,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2092621284944,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df_nodes.columns

Index(['ASCII_SPACES', 'DEFAULT_BUILDER_FEATURES_0',
       'DEFAULT_BUILDER_FEATURES_1', 'ROOT_TAG_NAME', 'can_be_empty_element',
       'contains_replacement_characters', 'contents_0', 'contents_1',
       'contents_3', 'contents_4',
       ...
       'attrs__data-has-widgets', 'attrs__data-layout', 'attrs__aria-modal',
       'attrs__data-dropdown-func', 'attrs__data-back-txt',
       'attrs__data-prepend-menu-mobile', 'attrs__version', 'attrs__cx',
       'attrs__cy', 'attrs__r'],
      dtype='str', length=839)

In [10]:
df_nodes[df_nodes.type == bs4.element.Tag]

,ASCII_SPACES,ROOT_TAG_NAME,can_be_empty_element,contains_replacement_characters,declared_html_encoding,decomposed,hidden,is_empty_element,is_xml,known_xml,...,nextSibling,next_element,next_sibling,string,previous,previousSibling,previous_element,previous_sibling,sourceline,sourcepos
pyid,,,,,,,,,,,,,,,,,,,,,
3042264323744,NaN,NaN,False,NaN,NaN,False,False,False,NaN,False,...,\n,NaN,\n,NaN,\n,\n,\n,\n,2.0,0.0
3042263850896,NaN,NaN,False,NaN,NaN,False,False,False,NaN,False,...,NaN,\n,NaN,NaN,NaN,NaN,NaN,NaN,2.0,120.0
3042263851536,NaN,NaN,True,NaN,NaN,False,False,True,NaN,False,...,NaN,NaN,NaN,NaN,\n,\n,\n,\n,3.0,0.0
3042228232592,NaN,NaN,False,NaN,NaN,False,False,False,NaN,False,...,\n,\n,\n,NaN,NaN,NaN,NaN,NaN,3.0,67.0
3042228232896,NaN,NaN,True,NaN,NaN,False,False,True,NaN,False,...,NaN,NaN,NaN,NaN,\n,\n,\n,\n,4.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3042270331472,NaN,NaN,False,NaN,NaN,False,False,False,NaN,False,...,\n,"\r\n{""baseUrl"":""https://s.w.org/images/core/em...",\n,"\r\n{""baseUrl"":""https://s.w.org/images/core/em...",\n,\n,\n,\n,2820.0,0.0
3042270331984,NaN,NaN,False,NaN,NaN,False,False,False,NaN,False,...,\n,\r\n/*! This file is auto-generated */\r\nvar ...,\n,\r\n/*! This file is auto-generated */\r\nvar ...,\n,\n,\n,\n,2823.0,0.0
3042270332240,NaN,NaN,False,NaN,NaN,False,False,False,NaN,False,...,NaN,NaN,NaN,NaN,\n,\n,\n,\n,2828.0,0.0
3042270332496,NaN,NaN,False,NaN,NaN,False,False,False,NaN,False,...,\n,"window.NREUM||(NREUM={});NREUM.info={""beacon"":...",\n,"window.NREUM||(NREUM={});NREUM.info={""beacon"":...",NaN,NaN,NaN,NaN,2828.0,81.0
3042270332752,NaN,NaN,False,NaN,NaN,False,False,False,NaN,False,...,NaN,\n,NaN,NaN,\n,NaN,\n,NaN,2831.0,7.0

In [133]:
sr = pd.Series(page.find_all())
sr.apply(type).value_counts()

<class 'bs4.element.Tag'>    3379
Name: count, dtype: int64

In [134]:
def leafs(node):
    child_count = 0
    if hasattr(node, "children"):
        for child in node.children:
            child_count += 1
            yield from leafs(child)
        if child_count == 0:
            yield node
    else:
        yield node

import pandas as pd
leafs_sr = pd.Series(leafs(page))
leafs_sr.name = "bs4"
leafs_sr.index = leafs_sr.apply(id)
df = pd.DataFrame(leafs_sr)
df.index.name="pyid"
df

                                                             bs4
pyid
1322756598160                                               html
1322756599312                                                 \n
1322756599696                                                 \n
1322740805456                                                 []
1322649963856                                                 []
...                                                          ...
1322758115152  window.NREUM||(NREUM={});NREUM.info={"beacon":...
1322758115248                                                 \n
1322758073168                                                 []
1322758115344                                                 \n
1322758115440   plugin=object-cache-pro client=phpredis metri...

[2915 rows x 1 columns]

In [135]:
df["type"] = leafs_sr.apply(type).apply(str).str.extract("'(.*)'")
df

,bs4,type
pyid,,
1322756598160,html,bs4.element.Doctype
1322756599312,\n,bs4.element.NavigableString
1322756599696,\n,bs4.element.NavigableString
1322740805456,[],bs4.element.Tag
1322649963856,[],bs4.element.Tag
...,...,...
1322758115152,"window.NREUM||(NREUM={});NREUM.info={""beacon"":...",bs4.element.Script
1322758115248,\n,bs4.element.NavigableString
1322758073168,[],bs4.element.Tag
1322758115344,\n,bs4.element.NavigableString
1322758115440,plugin=object-cache-pro client=phpredis metri...,bs4.element.Comment

In [136]:
df["text"] = df.bs4.apply(lambda t: None if t.text.strip() == "" else t.text.strip())
df

,bs4,type,text
pyid,,,
1322756598160,html,bs4.element.Doctype,NaN
1322756599312,\n,bs4.element.NavigableString,NaN
1322756599696,\n,bs4.element.NavigableString,NaN
1322740805456,[],bs4.element.Tag,NaN
1322649963856,[],bs4.element.Tag,NaN
...,...,...,...
1322758115152,"window.NREUM||(NREUM={});NREUM.info={""beacon"":...",bs4.element.Script,NaN
1322758115248,\n,bs4.element.NavigableString,NaN
1322758073168,[],bs4.element.Tag,NaN
1322758115344,\n,bs4.element.NavigableString,NaN
1322758115440,plugin=object-cache-pro client=phpredis metri...,bs4.element.Comment,NaN

In [137]:
df = df.dropna()
df.to_csv("pytorch_texts.csv")
df

,bs4,type,text
pyid,,,
1322756597488,Previous PyTorch Versions,bs4.element.NavigableString,Previous PyTorch Versions
1322752547664,Skip to main content,bs4.element.NavigableString,Skip to main content
1322752541712,Join us at PyTorch Conference North America · ...,bs4.element.NavigableString,Join us at PyTorch Conference North America · ...
1322752544976,Search,bs4.element.NavigableString,Search
1322752546896,Close Search,bs4.element.NavigableString,Close Search
...,...,...,...
1322757925936,Staff,bs4.element.NavigableString,Staff
1322757926128,Contact,bs4.element.NavigableString,Contact
1322757926416,Brand Guidelines,bs4.element.NavigableString,Brand Guidelines
1322757926704,JOIN,bs4.element.NavigableString,JOIN
1322757928048,Menu,bs4.element.NavigableString,Menu

In [138]:
bs_item = df.bs4.iloc[0]
bs_item, bs_item.parent, bs_item.parent.parent, bs_item.parent.parent.parent

('Previous PyTorch Versions',
 <title>Previous PyTorch Versions</title>,
 <head>
 <meta content="text/html; charset=utf-8" http-equiv="content-type"/><style data-hubspot-styled-components=""></style>
 <meta charset="utf-8"/><script async=""></script><script type="text/javascript">(window.NREUM||(NREUM={})).init={privacy:{cookies_enabled:true},ajax:{deny_list:["bam.nr-data.net"]},distributed_tracing:{enabled:true}};(window.NREUM||(NREUM={})).loader_config={agentID:"718404699",accountID:"6722501",trustKey:"66686",xpid:"UgEFU1NTCRAGXVdTAgQFVFU=",licenseKey:"NRJS-82305f38d28401c8ce5",applicationID:"696155221",browserID:"718404699"};;/*! For license information please see nr-loader-spa-1.321.0.min.js.LICENSE.txt */

In [139]:
#FIXME: this is buggy.
def parent_id_chain(node, visited=None):
    if visited is None:
        visited = set()
    yield id(node)
    visited.add(id(node))
    if hasattr(node, "parent") and id(node.parent) not in visited:
        yield from parent_chain(node.parent, visited=visited)

def parent_id_chain(node, visited=None):
    visited = visited or set()
    while node and id(node) not in visited:
        yield id(node)
        visited.add(id(node))
        node = getattr(node, "parent", None)

parent_id_df = df.bs4.apply(parent_id_chain).apply(pd.Series)
parent_id_df.to_csv("parent_ids.csv")
depths = parent_id_df.columns
depths

RangeIndex(start=0, stop=23, step=1)

In [140]:
for i in depths:
    vc = parent_id_df[i].value_counts()
    display(vc[vc > 1])

Series([], Name: count, dtype: int64)

1
1.322758e+12    5
1.322757e+12    3
1.322753e+12    2
1.322757e+12    2
1.322757e+12    2
1.322758e+12    2
Name: count, dtype: int64

2
1.322753e+12    328
1.322757e+12    255
1.322757e+12      5
1.322758e+12      5
1.322757e+12      4
1.322758e+12      4
1.322753e+12      2
1.322757e+12      2
1.322757e+12      2
1.322757e+12      2
1.322757e+12      2
1.322758e+12      2
Name: count, dtype: int64

3
1.322753e+12    328
1.322757e+12    255
1.322757e+12     63
1.322757e+12     50
1.322757e+12     24
1.322753e+12     23
1.322758e+12     10
1.322758e+12      8
1.322758e+12      7
1.322758e+12      7
1.322758e+12      7
1.322753e+12      6
1.322757e+12      5
1.322758e+12      5
1.322758e+12      4
1.322758e+12      4
1.322753e+12      2
1.322757e+12      2
1.322757e+12      2
1.322757e+12      2
1.322758e+12      2
1.322758e+12      2
Name: count, dtype: int64

4
1.322753e+12    328
1.322757e+12    255
1.322753e+12    142
1.322753e+12     23
1.322750e+12     10
1.322758e+12     10
1.322750e+12      8
1.322758e+12      8
1.322750e+12      7
1.322750e+12      7
1.322750e+12      7
1.322758e+12      7
1.322758e+12      7
1.322758e+12      7
1.322758e+12      7
1.322753e+12      6
1.322758e+12      5
1.322750e+12      4
1.322758e+12      4
1.322758e+12      4
1.322757e+12      3
1.322750e+12      2
1.322753e+12      2
1.322757e+12      2
1.322757e+12      2
1.322757e+12      2
1.322758e+12      2
Name: count, dtype: int64

5
1.322753e+12    328
1.322757e+12    256
1.322753e+12    142
1.322758e+12     38
1.322753e+12     23
1.322750e+12     10
1.322750e+12      8
1.322750e+12      7
1.322750e+12      7
1.322750e+12      7
1.322758e+12      7
1.322758e+12      7
1.322753e+12      6
1.322758e+12      5
1.322750e+12      4
1.322758e+12      4
1.322757e+12      3
1.322750e+12      2
1.322753e+12      2
1.322757e+12      2
1.322757e+12      2
1.322757e+12      2
Name: count, dtype: int64

6
1.322753e+12    328
1.322757e+12    256
1.322753e+12    164
1.322753e+12    142
1.322750e+12     38
1.322758e+12     38
1.322753e+12     23
1.322750e+12      7
1.322758e+12      7
1.322750e+12      7
1.322758e+12      7
1.322753e+12      6
1.322757e+12      6
1.322758e+12      4
1.322757e+12      3
1.322753e+12      2
Name: count, dtype: int64

7
1.322753e+12    328
1.322757e+12    256
1.322753e+12    164
1.322753e+12    142
1.322750e+12     38
1.322758e+12     38
1.322753e+12     23
1.322752e+12      8
1.322750e+12      7
1.322758e+12      7
1.322758e+12      7
1.322753e+12      6
1.322757e+12      6
1.322750e+12      4
1.322757e+12      3
1.322752e+12      2
1.322753e+12      2
Name: count, dtype: int64

8
1.322753e+12    328
1.322757e+12    256
1.322753e+12    164
1.322753e+12    164
1.322753e+12    142
1.322750e+12     38
1.322758e+12     38
1.322753e+12     23
1.322741e+12      8
1.322750e+12      7
1.322757e+12      7
1.322758e+12      7
1.322750e+12      7
1.322752e+12      6
1.322753e+12      6
1.322757e+12      3
1.322757e+12      3
1.322753e+12      2
Name: count, dtype: int64

9
1.322753e+12    328
1.322757e+12    256
1.322753e+12    164
1.322753e+12    164
1.322753e+12    142
1.322750e+12     38
1.322758e+12     38
1.322753e+12     24
1.322744e+12      8
1.322750e+12      7
1.322757e+12      7
1.322750e+12      7
1.322752e+12      7
1.322741e+12      6
1.322753e+12      6
1.322757e+12      3
1.322757e+12      3
1.322752e+12      2
1.322753e+12      2
Name: count, dtype: int64

10
1.322753e+12    328
1.322757e+12    256
1.322753e+12    164
1.322753e+12    164
1.322753e+12    142
1.322750e+12     38
1.322750e+12     38
1.322753e+12     24
1.322752e+12      9
1.322752e+12      7
1.322750e+12      7
1.322741e+12      7
1.322744e+12      6
1.322753e+12      6
1.322757e+12      4
1.322757e+12      3
1.322753e+12      2
Name: count, dtype: int64

11
1.322753e+12    328
1.322757e+12    256
1.322753e+12    164
1.322753e+12    164
1.322753e+12    142
1.322752e+12     45
1.322750e+12     38
1.322753e+12     24
1.322741e+12      9
1.322750e+12      7
1.322744e+12      7
1.322753e+12      6
1.322757e+12      4
1.322750e+12      3
1.322753e+12      2
Name: count, dtype: int64

12
1.322750e+12    332
1.322757e+12    256
1.322753e+12    164
1.322753e+12    164
1.322753e+12    142
1.322741e+12     45
1.322752e+12     38
1.322753e+12     24
1.322744e+12      9
1.322752e+12      8
1.322753e+12      6
1.322750e+12      4
1.322753e+12      2
Name: count, dtype: int64

13
1.322750e+12    332
1.322757e+12    256
1.322753e+12    164
1.322753e+12    164
1.322753e+12    142
1.322744e+12     45
1.322752e+12     42
1.322750e+12     24
1.322741e+12      8
1.322753e+12      6
1.322753e+12      3
Name: count, dtype: int64

14
1.322752e+12    332
1.322757e+12    256
1.322753e+12    165
1.322753e+12    164
1.322750e+12    142
1.322741e+12     42
1.322750e+12     24
1.322744e+12      8
1.322753e+12      6
1.322753e+12      3
Name: count, dtype: int64

15
1.322741e+12    332
1.322757e+12    256
1.322753e+12    165
1.322753e+12    164
1.322750e+12    142
1.322744e+12     42
1.322752e+12     25
1.322753e+12      6
1.322750e+12      4
Name: count, dtype: int64

16
1.322750e+12    421
1.322744e+12    332
1.322753e+12    170
1.322752e+12    142
1.322741e+12     25
1.322750e+12      4
Name: count, dtype: int64

17
1.322750e+12    421
1.322753e+12    170
1.322741e+12    142
1.322744e+12     25
1.322752e+12      4
Name: count, dtype: int64

18
1.322752e+12    421
1.322750e+12    170
1.322744e+12    142
1.322741e+12      4
Name: count, dtype: int64

19
1.322741e+12    421
1.322750e+12    170
1.322744e+12      4
Name: count, dtype: int64

20
1.322744e+12    421
1.322752e+12    170
Name: count, dtype: int64

21
1.322741e+12    170
Name: count, dtype: int64

22
1.322744e+12    170
Name: count, dtype: int64